version: '3.1'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: app
      APP_USER_PASSWORD: app
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "app/app@localhost/XEPDB1", "-c", "SELECT 1 FROM DUAL;"]
      interval: 30s
      timeout: 10s
      retries: 10

volumes:
  oracle-data:
